### ISSUE TITLE
Should protect flush_all call in memcache_queue_client

### ISSUE THREAD

**Issue by aselder** [derfred/workling#1]
Starling does not support the flush_all command (I've filed a bug against starling btw), but until that is fixed, workling throws an error every time it tries to disconnect from Starling.

Here's how I modified my copy of workling to get it to work:

```
  # closes the memcache connection
  def close
    begin
      self.connection.flush_all
    rescue MemCache::MemCacheError => err
      STDERR.puts "Memcache client doesn't respond to flush all"
    ensure
      self.connection.reset
    end
  end
```

**Comment by derfred** [comment]
sorry I missed this entry. Is the issue still valid?

**Comment by aselder** [comment]
Yes, this is still a valid issue.
It's in the memcache_queue_client.rb file around line 50.

Thanks,

Andrew

**Comment by derfred** [comment]
just pushed the patch through and cut a new version of the gem (0.4.9.8)
