### ISSUE TITLE
 uninitialized constant Workling (NameError)

### ISSUE THREAD

**Issue by constantine-nikolaou** [derfred/workling#4]
When I run workling_daemon.rb with params using

ruby script/workling_client run

I get the following:

App/config/environments/development.rb:28: uninitialized constant Workling (NameError)
    from /Users/user/.rvm/gems/ree-1.8.7-2011.03@global/gems/railties-3.0.10/lib/rails/application.rb:47:in `class_eval'
    from /Users/user/.rvm/gems/ree-1.8.7-2011.03@global/gems/railties-3.0.10/lib/rails/application.rb:47:in`configure'
    from /Users/user/dev/mekentosj/Livfe-Framework/config/environments/development.rb:1
....

My environment development.rb file has the following before the closing end:

  Workling::Remote.dispatcher = Workling::Remote::Runners::ClientRunner.new
  Workling::Remote.dispatcher.client = Workling::Clients::SqsClient.new

What am i missing?

**Comment by derfred** [comment]
do you have the following line in your environment.rb:

config.gem "workling"

?

**Comment by constantine-nikolaou** [comment]
Hey, thanks for that.

I didn't know that workling is now a gem...

I'll give it a try, thanks again
